Rework war mechanics, Misc changes
crusalis/multi-nodes pull request #4
Opened 2022-12-05 04:23 UTC by Kali0033

Sorry for the mega-commit in advance, this commit changes a substantial amount of the war mechanics, general utility and expands out configuration options.

Addresses issues currently marked in project.

Has had preliminary testing but will require more substantial testing before merged into master.

2022-12-05 15:15 UTC, Maldaris requested changes
Looks good overall from a general implementation standpoint, couple small gotchas, and one code layout concern.

Will need to test it in-game as well.

2022-12-05 15:15 UTC, Maldaris commented on nodes/src/main/kotlin/phonon/nodes/commands/TargetTownCommand.kt
> +        if (contextnation == null && contextTown == null) {
This should probably be a `||`

2022-12-05 15:15 UTC, Maldaris commented on nodes/src/main/kotlin/phonon/nodes/commands/TargetTownCommand.kt
> +        if (args.size == 1 && town !== null && nation == null && contextnation !== null) {
There a ton of these conditionals that are not immediately legible as to what each conditional check is trying to achieve (targeting town, nation, etc). It would be better to break the body of the if statement in each case out into a function, name the function as to the intent, and invoke the function here. Better still, we can add a function to combine these checks into a single variable, like an integer flag or an enum, and then use a switch statement to invoke the appropriate strategy's function.

In general, if we're making 3-4 boolean checks in a single if case, we should look to see how we can simplify the expression and structure code for readability/maintainability.

2022-12-05 15:35 UTC, Maldaris commented
In addition, make sure we get the manual test cases written out as well.

2022-12-07 08:33 UTC, Kali0033 commented on nodes/src/main/kotlin/phonon/nodes/commands/AllyCommand.kt
> +            Message.error(player, "Only nations can form alliances")
Added return statement for next commit.

2022-12-07 08:35 UTC, Kali0033 commented on nodes/src/main/kotlin/phonon/nodes/commands/NodesAdminCommand.kt
> +                        warvt.targetTown == null
Fixed double equals, agreed with alerting towns. At present there is no easy method to do this but will add in a new Broadcast utils class to simplify this for both this use-case/future uses.

2022-12-07 08:35 UTC, Kali0033 commented on nodes/src/main/kotlin/phonon/nodes/commands/NodesAdminCommand.kt
> +                        war.targetTown == null
Fixed in upcoming commit.

2022-12-07 08:35 UTC, Kali0033 commented on nodes/src/main/kotlin/phonon/nodes/commands/NodesAdminCommand.kt
> +                        war.targetTown == targetTown
Fixed in upcoming commit.

2022-12-07 08:35 UTC, Kali0033 commented on nodes/src/main/kotlin/phonon/nodes/commands/NodesAdminCommand.kt
> +                        warvt.targetTown == targetTown
Fixed in upcoming commit.

2022-12-07 08:36 UTC, Kali0033 commented on nodes/src/main/kotlin/phonon/nodes/commands/SurrenderCommand.kt
> +        parseNationName(player, args, town, town.nation)
Agreed method is poorly named, will overhaul this class/its respective methods.

2022-12-07 08:36 UTC, Kali0033 commented on nodes/src/main/kotlin/phonon/nodes/commands/TargetTownCommand.kt
> +        if (contextnation == null && contextTown == null) {
Intentional, functions as a check incase there is no nation or town possible. (since in wars it is possible to target a town in a nation vs town war).

2022-12-09 17:10 UTC, Maldaris approved these changes

2022-12-09 17:10 UTC, merged